import type { Metadata } from "next";
import { notFound } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getUser() {
    throw new Error("Function not implemented.");
}

function isAdmin(user: any) {
    throw new Error("Function not implemented.");
}
export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>{children}</>);
}




